// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/acepanel/backup-template/internal/app"
	"github.com/acepanel/backup-template/internal/bootstrap"
	"github.com/acepanel/backup-template/internal/route"
	"github.com/acepanel/backup-template/internal/service"
)

// Injectors from wire.go:

// initCli init command line.
func initCli() (*app.Cli, error) {
	koanf, err := bootstrap.NewConf()
	if err != nil {
		return nil, err
	}
	locale, err := bootstrap.NewT(koanf)
	if err != nil {
		return nil, err
	}
	cliService := service.NewCliService(locale, koanf)
	cli := route.NewCli(locale, cliService)
	command := bootstrap.NewCli(locale, cli)
	appCli := app.NewCli(command)
	return appCli, nil
}
